spring:
  datasource:
    username: test
    url: jdbc:mysql://localhost:3306/basics?allowPublicKeyRetrieval=true
    password: my-sql-database-pass
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

